config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [ :index, :show ] do
    resource :likes, only: [ :create ]
  end
  root 'games#index'
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :likes
  validates :name, presence: true, uniqueness: true
  scope :active, -> { where(active: true) }
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :game
  validates :ip, uniqueness: { scope: :game_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    games = Services::GamesFetcher.list
    @games = games.map{|g| Presenters::Game.new g }
  end

  def show
    game = Game.find params[:id]
    @game = Presenters::Game.new game
    render partial: 'show'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    form = Forms::Like.new request, form_params
    if form.save
      @game = Presenters::Game.new(Game.find(params[:game_id]))
      render partial: 'games/show'
    else
      render json: { message: form.errors.full_messages }, status: 422
    end
  end

  private

  def form_params
    params.permit(*Forms::Like.attributes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_show.html.erb
<%= csrf_meta_tag %>
<div id='error'></div>
<dl>
  <dt>Name:</dt>
  <dd><%= @game.name %></dd>
  <dt>Manufacturer:</dt>
  <dd><%= @game.manufacturer %></dd>
  <dt>Notes:</dt>
  <dd><%= @game.notes %></dd>
  <dt>Liked:</dt>
  <dd><%= @game.liked_count %></dd>
  <dt>Active:</dt>
  <dd><%= @game.active %></dd>
  <dt>Photo:</dt>
  <dd>
    <%= image_tag(@game.photo, alt: "Not Available", width: @game.photo_width, height: @game.photo_height) %>
  </dd>
</dl>

<div>
  <% if @game.liked_by?(request.remote_ip) %>
    Liked
  <% else %>
    <%= link_to "Like", game_likes_path(game_id: @game.id), {class: 'like'} %>
  <% end %>
</div>

app/views/games/index.html.erb
<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Publisher</th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game|%>
      <tr>
        <td><a class="game-show" href=<%= game_path(game.id)%>><%= game.name %></a></td>
        <td><%= game.manufacturer %></td>
      </tr>
    <%end%>
  </tbody>
</table>

<script type='text/javascript'>
  $(function() {
    window.games.getReady();
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Class Arcade Games</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>